# Generated by Django 5.1 on 2024-08-24 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("fitness_app", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="diet",
            name="name",
        ),
        migrations.AddField(
            model_name="diet",
            name="carbohydrates",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="diet",
            name="protein",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="diet",
            name="water",
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="diet",
            name="calories",
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="workout",
            name="description",
            field=models.TextField(blank=True),
        ),
    ]
